server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.55.241.179:3306/tutu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.tutu.shopplatform.domain
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
